USE [master]
GO

/****** Object:  Database [prj301_daigakusei]    Script Date: 7/16/2025 3:14:34 PM ******/
CREATE DATABASE [prj301_daigakusei]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'prj301_daigakusei', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\prj301_daigakusei.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'prj301_daigakusei_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\prj301_daigakusei_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [prj301_daigakusei].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [prj301_daigakusei] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [prj301_daigakusei] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [prj301_daigakusei] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [prj301_daigakusei] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [prj301_daigakusei] SET ARITHABORT OFF 
GO

ALTER DATABASE [prj301_daigakusei] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [prj301_daigakusei] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [prj301_daigakusei] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [prj301_daigakusei] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [prj301_daigakusei] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [prj301_daigakusei] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [prj301_daigakusei] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [prj301_daigakusei] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [prj301_daigakusei] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [prj301_daigakusei] SET  DISABLE_BROKER 
GO

ALTER DATABASE [prj301_daigakusei] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [prj301_daigakusei] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [prj301_daigakusei] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [prj301_daigakusei] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [prj301_daigakusei] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [prj301_daigakusei] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [prj301_daigakusei] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [prj301_daigakusei] SET RECOVERY FULL 
GO

ALTER DATABASE [prj301_daigakusei] SET  MULTI_USER 
GO

ALTER DATABASE [prj301_daigakusei] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [prj301_daigakusei] SET DB_CHAINING OFF 
GO

ALTER DATABASE [prj301_daigakusei] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [prj301_daigakusei] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [prj301_daigakusei] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [prj301_daigakusei] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [prj301_daigakusei] SET QUERY_STORE = ON
GO

ALTER DATABASE [prj301_daigakusei] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [prj301_daigakusei] SET  READ_WRITE 
GO


